# Generated by Django 4.2 on 2023-09-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItiems',
            new_name='OrderItiem',
        ),
    ]
