# Generated by Django 4.2 on 2023-09-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_orderitiems_orderitiem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItiem',
            new_name='OrderItem',
        ),
    ]
